{
 "title": "RB11E",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "devEui",
    "label": "Selected Sensor",
    "query": "SELECT Name || '-' || DevEui as Name_DevEui FROM $__database.\"sensor_list\" where Name != ''  and measure_value::varchar = 'CREATED' and Model = '${model}' and Vendor = '${vendor}'"
   },
   { "name": "vendor", "label": "Vendor", "query": "Netvox" },
   { "name": "model", "label": "Model", "query": "RB11E" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"lorawandash_db\"",
     "measure": "humidity",
     "rawQuery": "select time,measure_value::double from $__database.$__table where measure_name='temperature' and DevEui = split_part('${devEui}', '-', 2) and $__timeFilter",
     "table": "\"sensor_data\""
    }
   ]
  },
  {
   "title": "Min temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Max temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "PIR Trigger count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"lorawandash_db\"",
     "measure": "humidity",
     "rawQuery": "select time, measure_value::double from $__database.$__table where measure_name='pir' and DevEui = split_part('${devEui}', '-', 2) and $__timeFilter",
     "table": "\"sensor_data\""
    }
   ]
  },
  {
   "title": "Lux level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"lorawandash_db\"",
     "measure": "humidity",
     "rawQuery": "select time, measure_value::double from $__database.$__table where measure_name='lux' and DevEui = split_part('${devEui}', '-', 2) and $__timeFilter",
     "table": "\"sensor_data\""
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Light level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "PIR activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 14 }
   ]
  }
 ]
}